/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HrRouteImport } from './routes/hr'
import { Route as CandidateRouteImport } from './routes/candidate'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HrIndexRouteImport } from './routes/hr.index'
import { Route as CandidateIndexRouteImport } from './routes/candidate.index'
import { Route as RegisterHrRouteImport } from './routes/register.hr'
import { Route as RegisterCandidateRouteImport } from './routes/register.candidate'
import { Route as LoginHrRouteImport } from './routes/login.hr'
import { Route as LoginCandidateRouteImport } from './routes/login.candidate'
import { Route as HrSettingsRouteImport } from './routes/hr.settings'
import { Route as HrReportsRouteImport } from './routes/hr.reports'
import { Route as HrJobsRouteImport } from './routes/hr.jobs'
import { Route as HrDashboardRouteImport } from './routes/hr.dashboard'
import { Route as HrCandidatesRouteImport } from './routes/hr.candidates'
import { Route as HrAssistantRouteImport } from './routes/hr.assistant'
import { Route as HrAiAnalysisRouteImport } from './routes/hr.ai-analysis'
import { Route as CandidateUploadRouteImport } from './routes/candidate.upload'
import { Route as CandidateProfileRouteImport } from './routes/candidate.profile'
import { Route as CandidateJobsRouteImport } from './routes/candidate.jobs'
import { Route as CandidateInterviewPrepRouteImport } from './routes/candidate.interview-prep'
import { Route as CandidateDashboardRouteImport } from './routes/candidate.dashboard'
import { Route as CandidateApplicationsRouteImport } from './routes/candidate.applications'
import { Route as HrCandidatesIdRouteImport } from './routes/hr.candidates.$id'

const HrRoute = HrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateRoute = CandidateRouteImport.update({
  id: '/candidate',
  path: '/candidate',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HrIndexRoute = HrIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HrRoute,
} as any)
const CandidateIndexRoute = CandidateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CandidateRoute,
} as any)
const RegisterHrRoute = RegisterHrRouteImport.update({
  id: '/register/hr',
  path: '/register/hr',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterCandidateRoute = RegisterCandidateRouteImport.update({
  id: '/register/candidate',
  path: '/register/candidate',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginHrRoute = LoginHrRouteImport.update({
  id: '/login/hr',
  path: '/login/hr',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginCandidateRoute = LoginCandidateRouteImport.update({
  id: '/login/candidate',
  path: '/login/candidate',
  getParentRoute: () => rootRouteImport,
} as any)
const HrSettingsRoute = HrSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => HrRoute,
} as any)
const HrReportsRoute = HrReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => HrRoute,
} as any)
const HrJobsRoute = HrJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => HrRoute,
} as any)
const HrDashboardRoute = HrDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => HrRoute,
} as any)
const HrCandidatesRoute = HrCandidatesRouteImport.update({
  id: '/candidates',
  path: '/candidates',
  getParentRoute: () => HrRoute,
} as any)
const HrAssistantRoute = HrAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => HrRoute,
} as any)
const HrAiAnalysisRoute = HrAiAnalysisRouteImport.update({
  id: '/ai-analysis',
  path: '/ai-analysis',
  getParentRoute: () => HrRoute,
} as any)
const CandidateUploadRoute = CandidateUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => CandidateRoute,
} as any)
const CandidateProfileRoute = CandidateProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => CandidateRoute,
} as any)
const CandidateJobsRoute = CandidateJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => CandidateRoute,
} as any)
const CandidateInterviewPrepRoute = CandidateInterviewPrepRouteImport.update({
  id: '/interview-prep',
  path: '/interview-prep',
  getParentRoute: () => CandidateRoute,
} as any)
const CandidateDashboardRoute = CandidateDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => CandidateRoute,
} as any)
const CandidateApplicationsRoute = CandidateApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => CandidateRoute,
} as any)
const HrCandidatesIdRoute = HrCandidatesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => HrCandidatesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/candidate': typeof CandidateRouteWithChildren
  '/hr': typeof HrRouteWithChildren
  '/candidate/applications': typeof CandidateApplicationsRoute
  '/candidate/dashboard': typeof CandidateDashboardRoute
  '/candidate/interview-prep': typeof CandidateInterviewPrepRoute
  '/candidate/jobs': typeof CandidateJobsRoute
  '/candidate/profile': typeof CandidateProfileRoute
  '/candidate/upload': typeof CandidateUploadRoute
  '/hr/ai-analysis': typeof HrAiAnalysisRoute
  '/hr/assistant': typeof HrAssistantRoute
  '/hr/candidates': typeof HrCandidatesRouteWithChildren
  '/hr/dashboard': typeof HrDashboardRoute
  '/hr/jobs': typeof HrJobsRoute
  '/hr/reports': typeof HrReportsRoute
  '/hr/settings': typeof HrSettingsRoute
  '/login/candidate': typeof LoginCandidateRoute
  '/login/hr': typeof LoginHrRoute
  '/register/candidate': typeof RegisterCandidateRoute
  '/register/hr': typeof RegisterHrRoute
  '/candidate/': typeof CandidateIndexRoute
  '/hr/': typeof HrIndexRoute
  '/hr/candidates/$id': typeof HrCandidatesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/candidate/applications': typeof CandidateApplicationsRoute
  '/candidate/dashboard': typeof CandidateDashboardRoute
  '/candidate/interview-prep': typeof CandidateInterviewPrepRoute
  '/candidate/jobs': typeof CandidateJobsRoute
  '/candidate/profile': typeof CandidateProfileRoute
  '/candidate/upload': typeof CandidateUploadRoute
  '/hr/ai-analysis': typeof HrAiAnalysisRoute
  '/hr/assistant': typeof HrAssistantRoute
  '/hr/candidates': typeof HrCandidatesRouteWithChildren
  '/hr/dashboard': typeof HrDashboardRoute
  '/hr/jobs': typeof HrJobsRoute
  '/hr/reports': typeof HrReportsRoute
  '/hr/settings': typeof HrSettingsRoute
  '/login/candidate': typeof LoginCandidateRoute
  '/login/hr': typeof LoginHrRoute
  '/register/candidate': typeof RegisterCandidateRoute
  '/register/hr': typeof RegisterHrRoute
  '/candidate': typeof CandidateIndexRoute
  '/hr': typeof HrIndexRoute
  '/hr/candidates/$id': typeof HrCandidatesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/candidate': typeof CandidateRouteWithChildren
  '/hr': typeof HrRouteWithChildren
  '/candidate/applications': typeof CandidateApplicationsRoute
  '/candidate/dashboard': typeof CandidateDashboardRoute
  '/candidate/interview-prep': typeof CandidateInterviewPrepRoute
  '/candidate/jobs': typeof CandidateJobsRoute
  '/candidate/profile': typeof CandidateProfileRoute
  '/candidate/upload': typeof CandidateUploadRoute
  '/hr/ai-analysis': typeof HrAiAnalysisRoute
  '/hr/assistant': typeof HrAssistantRoute
  '/hr/candidates': typeof HrCandidatesRouteWithChildren
  '/hr/dashboard': typeof HrDashboardRoute
  '/hr/jobs': typeof HrJobsRoute
  '/hr/reports': typeof HrReportsRoute
  '/hr/settings': typeof HrSettingsRoute
  '/login/candidate': typeof LoginCandidateRoute
  '/login/hr': typeof LoginHrRoute
  '/register/candidate': typeof RegisterCandidateRoute
  '/register/hr': typeof RegisterHrRoute
  '/candidate/': typeof CandidateIndexRoute
  '/hr/': typeof HrIndexRoute
  '/hr/candidates/$id': typeof HrCandidatesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/candidate'
    | '/hr'
    | '/candidate/applications'
    | '/candidate/dashboard'
    | '/candidate/interview-prep'
    | '/candidate/jobs'
    | '/candidate/profile'
    | '/candidate/upload'
    | '/hr/ai-analysis'
    | '/hr/assistant'
    | '/hr/candidates'
    | '/hr/dashboard'
    | '/hr/jobs'
    | '/hr/reports'
    | '/hr/settings'
    | '/login/candidate'
    | '/login/hr'
    | '/register/candidate'
    | '/register/hr'
    | '/candidate/'
    | '/hr/'
    | '/hr/candidates/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/candidate/applications'
    | '/candidate/dashboard'
    | '/candidate/interview-prep'
    | '/candidate/jobs'
    | '/candidate/profile'
    | '/candidate/upload'
    | '/hr/ai-analysis'
    | '/hr/assistant'
    | '/hr/candidates'
    | '/hr/dashboard'
    | '/hr/jobs'
    | '/hr/reports'
    | '/hr/settings'
    | '/login/candidate'
    | '/login/hr'
    | '/register/candidate'
    | '/register/hr'
    | '/candidate'
    | '/hr'
    | '/hr/candidates/$id'
  id:
    | '__root__'
    | '/'
    | '/candidate'
    | '/hr'
    | '/candidate/applications'
    | '/candidate/dashboard'
    | '/candidate/interview-prep'
    | '/candidate/jobs'
    | '/candidate/profile'
    | '/candidate/upload'
    | '/hr/ai-analysis'
    | '/hr/assistant'
    | '/hr/candidates'
    | '/hr/dashboard'
    | '/hr/jobs'
    | '/hr/reports'
    | '/hr/settings'
    | '/login/candidate'
    | '/login/hr'
    | '/register/candidate'
    | '/register/hr'
    | '/candidate/'
    | '/hr/'
    | '/hr/candidates/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CandidateRoute: typeof CandidateRouteWithChildren
  HrRoute: typeof HrRouteWithChildren
  LoginCandidateRoute: typeof LoginCandidateRoute
  LoginHrRoute: typeof LoginHrRoute
  RegisterCandidateRoute: typeof RegisterCandidateRoute
  RegisterHrRoute: typeof RegisterHrRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/hr': {
      id: '/hr'
      path: '/hr'
      fullPath: '/hr'
      preLoaderRoute: typeof HrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate': {
      id: '/candidate'
      path: '/candidate'
      fullPath: '/candidate'
      preLoaderRoute: typeof CandidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr/': {
      id: '/hr/'
      path: '/'
      fullPath: '/hr/'
      preLoaderRoute: typeof HrIndexRouteImport
      parentRoute: typeof HrRoute
    }
    '/candidate/': {
      id: '/candidate/'
      path: '/'
      fullPath: '/candidate/'
      preLoaderRoute: typeof CandidateIndexRouteImport
      parentRoute: typeof CandidateRoute
    }
    '/register/hr': {
      id: '/register/hr'
      path: '/register/hr'
      fullPath: '/register/hr'
      preLoaderRoute: typeof RegisterHrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/candidate': {
      id: '/register/candidate'
      path: '/register/candidate'
      fullPath: '/register/candidate'
      preLoaderRoute: typeof RegisterCandidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/hr': {
      id: '/login/hr'
      path: '/login/hr'
      fullPath: '/login/hr'
      preLoaderRoute: typeof LoginHrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/candidate': {
      id: '/login/candidate'
      path: '/login/candidate'
      fullPath: '/login/candidate'
      preLoaderRoute: typeof LoginCandidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr/settings': {
      id: '/hr/settings'
      path: '/settings'
      fullPath: '/hr/settings'
      preLoaderRoute: typeof HrSettingsRouteImport
      parentRoute: typeof HrRoute
    }
    '/hr/reports': {
      id: '/hr/reports'
      path: '/reports'
      fullPath: '/hr/reports'
      preLoaderRoute: typeof HrReportsRouteImport
      parentRoute: typeof HrRoute
    }
    '/hr/jobs': {
      id: '/hr/jobs'
      path: '/jobs'
      fullPath: '/hr/jobs'
      preLoaderRoute: typeof HrJobsRouteImport
      parentRoute: typeof HrRoute
    }
    '/hr/dashboard': {
      id: '/hr/dashboard'
      path: '/dashboard'
      fullPath: '/hr/dashboard'
      preLoaderRoute: typeof HrDashboardRouteImport
      parentRoute: typeof HrRoute
    }
    '/hr/candidates': {
      id: '/hr/candidates'
      path: '/candidates'
      fullPath: '/hr/candidates'
      preLoaderRoute: typeof HrCandidatesRouteImport
      parentRoute: typeof HrRoute
    }
    '/hr/assistant': {
      id: '/hr/assistant'
      path: '/assistant'
      fullPath: '/hr/assistant'
      preLoaderRoute: typeof HrAssistantRouteImport
      parentRoute: typeof HrRoute
    }
    '/hr/ai-analysis': {
      id: '/hr/ai-analysis'
      path: '/ai-analysis'
      fullPath: '/hr/ai-analysis'
      preLoaderRoute: typeof HrAiAnalysisRouteImport
      parentRoute: typeof HrRoute
    }
    '/candidate/upload': {
      id: '/candidate/upload'
      path: '/upload'
      fullPath: '/candidate/upload'
      preLoaderRoute: typeof CandidateUploadRouteImport
      parentRoute: typeof CandidateRoute
    }
    '/candidate/profile': {
      id: '/candidate/profile'
      path: '/profile'
      fullPath: '/candidate/profile'
      preLoaderRoute: typeof CandidateProfileRouteImport
      parentRoute: typeof CandidateRoute
    }
    '/candidate/jobs': {
      id: '/candidate/jobs'
      path: '/jobs'
      fullPath: '/candidate/jobs'
      preLoaderRoute: typeof CandidateJobsRouteImport
      parentRoute: typeof CandidateRoute
    }
    '/candidate/interview-prep': {
      id: '/candidate/interview-prep'
      path: '/interview-prep'
      fullPath: '/candidate/interview-prep'
      preLoaderRoute: typeof CandidateInterviewPrepRouteImport
      parentRoute: typeof CandidateRoute
    }
    '/candidate/dashboard': {
      id: '/candidate/dashboard'
      path: '/dashboard'
      fullPath: '/candidate/dashboard'
      preLoaderRoute: typeof CandidateDashboardRouteImport
      parentRoute: typeof CandidateRoute
    }
    '/candidate/applications': {
      id: '/candidate/applications'
      path: '/applications'
      fullPath: '/candidate/applications'
      preLoaderRoute: typeof CandidateApplicationsRouteImport
      parentRoute: typeof CandidateRoute
    }
    '/hr/candidates/$id': {
      id: '/hr/candidates/$id'
      path: '/$id'
      fullPath: '/hr/candidates/$id'
      preLoaderRoute: typeof HrCandidatesIdRouteImport
      parentRoute: typeof HrCandidatesRoute
    }
  }
}

interface CandidateRouteChildren {
  CandidateApplicationsRoute: typeof CandidateApplicationsRoute
  CandidateDashboardRoute: typeof CandidateDashboardRoute
  CandidateInterviewPrepRoute: typeof CandidateInterviewPrepRoute
  CandidateJobsRoute: typeof CandidateJobsRoute
  CandidateProfileRoute: typeof CandidateProfileRoute
  CandidateUploadRoute: typeof CandidateUploadRoute
  CandidateIndexRoute: typeof CandidateIndexRoute
}

const CandidateRouteChildren: CandidateRouteChildren = {
  CandidateApplicationsRoute: CandidateApplicationsRoute,
  CandidateDashboardRoute: CandidateDashboardRoute,
  CandidateInterviewPrepRoute: CandidateInterviewPrepRoute,
  CandidateJobsRoute: CandidateJobsRoute,
  CandidateProfileRoute: CandidateProfileRoute,
  CandidateUploadRoute: CandidateUploadRoute,
  CandidateIndexRoute: CandidateIndexRoute,
}

const CandidateRouteWithChildren = CandidateRoute._addFileChildren(
  CandidateRouteChildren,
)

interface HrCandidatesRouteChildren {
  HrCandidatesIdRoute: typeof HrCandidatesIdRoute
}

const HrCandidatesRouteChildren: HrCandidatesRouteChildren = {
  HrCandidatesIdRoute: HrCandidatesIdRoute,
}

const HrCandidatesRouteWithChildren = HrCandidatesRoute._addFileChildren(
  HrCandidatesRouteChildren,
)

interface HrRouteChildren {
  HrAiAnalysisRoute: typeof HrAiAnalysisRoute
  HrAssistantRoute: typeof HrAssistantRoute
  HrCandidatesRoute: typeof HrCandidatesRouteWithChildren
  HrDashboardRoute: typeof HrDashboardRoute
  HrJobsRoute: typeof HrJobsRoute
  HrReportsRoute: typeof HrReportsRoute
  HrSettingsRoute: typeof HrSettingsRoute
  HrIndexRoute: typeof HrIndexRoute
}

const HrRouteChildren: HrRouteChildren = {
  HrAiAnalysisRoute: HrAiAnalysisRoute,
  HrAssistantRoute: HrAssistantRoute,
  HrCandidatesRoute: HrCandidatesRouteWithChildren,
  HrDashboardRoute: HrDashboardRoute,
  HrJobsRoute: HrJobsRoute,
  HrReportsRoute: HrReportsRoute,
  HrSettingsRoute: HrSettingsRoute,
  HrIndexRoute: HrIndexRoute,
}

const HrRouteWithChildren = HrRoute._addFileChildren(HrRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CandidateRoute: CandidateRouteWithChildren,
  HrRoute: HrRouteWithChildren,
  LoginCandidateRoute: LoginCandidateRoute,
  LoginHrRoute: LoginHrRoute,
  RegisterCandidateRoute: RegisterCandidateRoute,
  RegisterHrRoute: RegisterHrRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
