"""Initial schema migration

Revision ID: 8ee04f655c9e
Revises: 
Create Date: 2026-07-17 00:14:21.755243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8ee04f655c9e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('education_required', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('jobs', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('jobs', 'title',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.create_index(op.f('ix_jobs_id'), 'jobs', ['id'], unique=False)
    op.create_foreign_key(None, 'jobs', 'users', ['created_by'], ['id'])
    op.add_column('resumes', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('resumes', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('resumes', 'resume_path',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_foreign_key(None, 'resumes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('users', 'password_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'password_hash',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'resumes', type_='foreignkey')
    op.alter_column('resumes', 'resume_path',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('resumes', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('resumes', 'created_at')
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_index(op.f('ix_jobs_id'), table_name='jobs')
    op.alter_column('jobs', 'title',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.drop_column('jobs', 'updated_at')
    op.drop_column('jobs', 'created_at')
    op.drop_column('jobs', 'education_required')
    # ### end Alembic commands ###
